### ISSUE TITLE
Can't see numbers with Chrome's new material design

### ISSUE THREAD

**Issue by 972creative** [alex-vv/chrome-load-timer#13]
Hi there

Love your plugin. Been using it for years.

With Chrome's new material design layout (I'm on PC) we can no longer see the numbers on the bar in chrome - we're forced to click inside for details. See screenshot at http://prntscr.com/chen6g.

Appreciate if you can fix this.

Thanks,
Todd

**Comment by alex-vv** [comment]
Hi Todd, 

Can you please provide a screenshot with a better quality? This image from your link looks very blurred and I cannot understand the problem from it.

Also please tell the Chrome and OS version just in case, so I can try to reproduce it.

**Comment by mixalisen** [comment]
Hi there,
i guess Todd means that the numbers are too small and it is difficult to read them.

Cheers
Michael

**Comment by alex-vv** [comment]
Sorry for the late reply. I checked this on Windows 7 and numbers are indeed smaller there than on MacOS. But I can't change this since Chrome only allows to set a badge text and a background color, not font size. I guess this problem affects all extensions which show numbers or text in the toolbar.
